services:
  db:
    environment:
      POSTGRES_USER: staging_user
      POSTGRES_PASSWORD: staging_password
      POSTGRES_DB: staging_ecom_db

  server:
    environment:
      - NODE_ENV=stage
      
  frontend:
    environment:
      - VITE_API_URL=http://server:5001/api/v1
