services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    # networks:
    #   - ecom_network
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "dev_user"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    restart: always
    # networks:
    #   - ecom_network  # Ajoute adminer au réseau personnalisé

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8081:8080"
    devices:
      - /dev/kmsg:/dev/kmsg
    # depends_on:
    #   - server
    #   - frontend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml' 
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug --cluster.advertise-address=0.0.0.0:9093

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/data:/var/lib/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - "3001:3000"


#   server:
#     build:
#       context: ./server
#     container_name: server
#     depends_on:
#       db:
#         condition: service_healthy
#     ports:
#       - "5001:3000"
#     volumes:
#       - server_data:/app
#     restart: always
#     networks:
#       - ecom_network  # Ajoute le serveur au réseau personnalisé

#   frontend:
#     build:
#       context: ./frontend
#       args:
#         VITE_API_URL: http://localhost:5001/api/v1
#     container_name: frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - server
#     restart: always
#     networks:
#       - ecom_network  # Ajoute le frontend au réseau personnalisé

volumes:
  alertmanager-data:
  postgres_data:
  # grafana_data:
#   server_data:

# networks:
#   ecom_network:
#     driver: bridge  # Crée un réseau personnalisé avec le driver "bridge"
