services:
  db:
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_ecom_db
    ports:
      - "5432:5432"  

  adminer:
    environment:
      ADMINER_DEFAULT_SERVER: db
  
  # server:
  #   environment:
  #     - NODE_ENV=dev
